services:
  postgres:
    env_file: .env
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vehicles
      - POSTGRES_PORT=5434
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - vehicle_network

  flyway:
    image: flyway/flyway
    volumes:
      - ./src/main/resources/db/migrations:/flyway/db/migrations
    command: -url=jdbc:postgresql://localhost:5434/vehicles -user=${DB_USERNAME} -password=${DB_PASSWORD} migrate
    depends_on:
      - postgres
    networks:
      - vehicle_network

volumes:
  db_data:
    driver: local

networks:
  vehicle_network:
    driver: bridge
